### ISSUE TITLE
Access is too broad

### ISSUE THREAD

**Issue by ah-OOG-ah** [ksucpea/bettercanvas#10]
Canvas URLs are in the form \<organization>.instructure.com—limiting permissions to access on the domain instructure.com should be sufficient.

**Comment by ksucpea** [comment]
Hello, I appreciate you taking the time to suggest this, however there is actually a very broad range of canvas urls. Specifically, I have received requests for these urls:
https://unr.canvaslms.com/
https://eagleonline.hccs.edu/
http://canvas.sydney.edu.au/
http://w3schools.com/
and a few others.

The extension still checks for canvas in the url, and only runs on those pages

**Comment by rabidgoat** [comment]
I am not comfortable giving full access to all my browser data.

Is it possible to allow the user to input their specific domain list as needed?
would this change the "This add-on needs to: Access your data for all websites"?
I am not a coder in any regard, however I try to limit access when possible,

**Comment by ksucpea** [comment]
> I am not comfortable giving full access to all my browser data.
> 
> Is it possible to allow the user to input their specific domain list as needed? would this change the "This add-on needs to: Access your data for all websites"? I am not a coder in any regard, however I try to limit access when possible,

This is possible and I think you have 2 options here, you could either download this repo as a zip, edit the files, and manually install the extension, or install the extension through the chrome store and change the site access after installing. 

If you want to do option 2, first install, pin the extension, then go to your canvas page, right click on the better canvas icon at the top right, click on "this can read and change site data" and change it to only your canvas page. If you want to do option 1 let me know because it's a little more work to get running.
